CREATE TABLE IF NOT EXISTS staff (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  email VARCHAR(254) NOT NULL,
  status BOOLEAN NOT NULL,
  registration DATE NOT NULL
);