mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: dev.itboot.mb.model
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    initialization-mode: always
    url: jdbc:mysql://*.*.ap-northeast-1.console.aws.amazon.com:3306/ebdb
    username: admin
    password: Salsa1201
