mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: dev.itboot.mb.model
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    initialization-mode: always
    #url: jdbc:mysql://*.*.ap-northeast-1.console.aws.amazon.com:3306/ebdb   
    url:  jdbc:postgresql://testdb.comzupi39iws.ap-northeast-1.rds.amazonaws.com:5432/testdb
    #username: admin
    username: postgres 
    password: u06PVzkkdiOCd4FNKND0
